from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from farms.models import Farm, Category


FARMS = [
    {
        "name": "TK Ranch",
        "slug": "tk-ranch",
        "description": "Pioneer of direct marketing grass-fed beef in Alberta since 1995. Also raises pasture-raised pork and soy/corn-free chicken. Home delivery across Alberta.",
        "address_display": "Hanna, AB",
        "latitude": 51.6414,
        "longitude": -111.8946,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "delivery", "online", "farmers_market"],
        "certifications": ["grass_fed", "pasture_raised", "free_range"],
        "contact_phone": "403-854-8532",
        "contact_email": "hello@tkranch.com",
        "contact_website": "https://www.tkranch.com",
    },
    {
        "name": "Sunworks Farm",
        "slug": "sunworks-farm",
        "description": "Certified Organic and Certified Humane farm raising chicken, pork, turkey, beef, bison, and eggs since 1997. Ron and Sheila Hamilton have farmed organically for over 25 years.",
        "address_display": "Armena, AB",
        "latitude": 52.8833,
        "longitude": -112.7667,
        "categories": ["meat-poultry", "eggs"],
        "sales_channels": ["farm_gate", "delivery", "online", "farmers_market"],
        "certifications": ["organic", "pasture_raised", "free_range"],
        "contact_phone": "780-672-9798",
        "contact_website": "https://sunworksfarm.com",
    },
    {
        "name": "Sage and Shepherd Ranch",
        "slug": "sage-and-shepherd-ranch",
        "description": "Ranching couple raising 100% pasture-raised, hormone-free, antibiotic-free, non-GMO beef. Alberta-wide shipping every Tuesday.",
        "address_display": "Southern Alberta",
        "latitude": 49.7000,
        "longitude": -113.0000,
        "categories": ["meat-poultry"],
        "sales_channels": ["delivery", "online"],
        "certifications": ["grass_fed", "pasture_raised", "non_gmo"],
        "contact_website": "https://sageandshepherdranch.com",
    },
    {
        "name": "Farmer Del",
        "slug": "farmer-del",
        "description": "100% grass-fed, grass-finished heritage beef (North Devon x Galloway) on certified organic pasture just north of St. Albert. No hormones, antibiotics, or synthetic chemicals.",
        "address_display": "St. Albert, AB",
        "latitude": 53.6810,
        "longitude": -113.6287,
        "categories": ["meat-poultry"],
        "sales_channels": ["delivery", "online", "farm_gate"],
        "certifications": ["organic", "grass_fed"],
        "contact_website": "https://www.farmerdel.com",
    },
    {
        "name": "Burke Creek Ranch",
        "slug": "burke-creek-ranch",
        "description": "Fifth-generation family ranch in Alberta's foothills raising grass-fed and finished beef for 130 years. No hormones or antibiotics. Sells quarter, half, and whole beef direct.",
        "address_display": "Pincher Creek, AB",
        "latitude": 49.4861,
        "longitude": -114.0000,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "delivery", "online"],
        "certifications": ["grass_fed", "pasture_raised"],
        "contact_website": "https://burkecreekranch.com",
    },
    {
        "name": "Dykshoorn Farms",
        "slug": "dykshoorn-farms",
        "description": "5th generation family farm. Ethically raised pastured beef with 21-day extended dry-age. Home and work delivery across Alberta.",
        "address_display": "Foremost, AB",
        "latitude": 49.4833,
        "longitude": -111.4500,
        "categories": ["meat-poultry"],
        "sales_channels": ["delivery", "online", "farm_gate"],
        "certifications": ["pasture_raised"],
        "contact_website": "https://dykshoornfarms.com",
    },
    {
        "name": "Blue Ridge Farms",
        "slug": "blue-ridge-farms",
        "description": "Premium AAA grass-fed beef and pastured pork. Farm store carries local veggies, bread, honey. Refrigerated shipping across Alberta.",
        "address_display": "Blue Ridge, AB",
        "latitude": 54.0833,
        "longitude": -116.3833,
        "categories": ["meat-poultry", "eggs"],
        "sales_channels": ["farm_gate", "delivery", "online"],
        "certifications": ["grass_fed", "pasture_raised"],
        "contact_website": "https://blueridgefarms.ca",
    },
    {
        "name": "Spragg's Meat Shop",
        "slug": "spraggs-meat-shop",
        "description": "Free-range pigs raised on pasture with all pork processed on-site. Also offer family-raised lamb. Retail locations in Calgary and Rosemary.",
        "address_display": "Rosemary, AB",
        "latitude": 50.9167,
        "longitude": -111.8833,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "farmers_market", "online"],
        "certifications": ["free_range", "pasture_raised"],
        "contact_phone": "403-378-3800",
        "contact_website": "https://www.spraggsmeatshop.com",
    },
    {
        "name": "Hoven Farms",
        "slug": "hoven-farms",
        "description": "Century-old regenerative family farm certified organic since 1997. Raises organic grass-finished beef plus seasonal chicken, pork, and pastured eggs.",
        "address_display": "Eckville, AB",
        "latitude": 52.3667,
        "longitude": -114.3667,
        "categories": ["meat-poultry", "eggs"],
        "sales_channels": ["delivery", "online", "farmers_market"],
        "certifications": ["organic", "grass_fed", "pasture_raised", "free_range"],
        "contact_phone": "403-302-2748",
        "contact_email": "thehovens@hovenfarms.com",
        "contact_website": "https://www.hovenfarms.com",
    },
    {
        "name": "Homeland Meats",
        "slug": "homeland-meats",
        "description": "Hutterite enterprise producing quality meat. Free-range chickens roam open pastures with natural diet. Serves Grande Prairie region.",
        "address_display": "Falher, AB",
        "latitude": 55.7333,
        "longitude": -117.1000,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "delivery"],
        "certifications": ["free_range", "pasture_raised"],
        "contact_website": "https://homelandmeats.ca",
    },
    {
        "name": "Peace Country Produce",
        "slug": "peace-country-produce",
        "description": "Organic 100% grass-fed Galloway beef raised sustainably in the Peace Country. Dry-aged and processed at local certified organic plant.",
        "address_display": "Rycroft, AB",
        "latitude": 55.9500,
        "longitude": -118.7667,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "delivery"],
        "certifications": ["organic", "grass_fed"],
        "contact_phone": "780-765-2171",
        "contact_email": "peacecountryproduce@yahoo.ca",
    },
    {
        "name": "Rocky View Bison",
        "slug": "rocky-view-bison",
        "description": "Family ranch raising pasture-fed bison. Free delivery on orders over $150 to Calgary, Airdrie, Cochrane, and Chestermere.",
        "address_display": "Rocky View County, AB",
        "latitude": 51.2000,
        "longitude": -114.2000,
        "categories": ["meat-poultry"],
        "sales_channels": ["delivery", "online", "farm_gate"],
        "certifications": ["pasture_raised"],
        "contact_website": "https://www.rockyviewbison.com",
    },
    {
        "name": "Thundering Ground Bison Ranch",
        "slug": "thundering-ground-bison-ranch",
        "description": "Plains bison raised on ecologically diverse land in Leduc County. No artificial growth stimulants. Found at Edmonton farmers market.",
        "address_display": "Calmar, AB",
        "latitude": 53.2667,
        "longitude": -113.8333,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "farmers_market", "online"],
        "certifications": ["pasture_raised"],
        "contact_phone": "780-719-7774",
        "contact_email": "thunderinggroundbisonranch@gmail.com",
        "contact_website": "https://www.thunderinggroundbisonranch.ca",
    },
    {
        "name": "True Grit Buffalo Ranch",
        "slug": "true-grit-buffalo-ranch",
        "description": "Bison ranch near Sherwood Park serving Edmonton and surrounding areas. Individual cuts, curated boxes, and quarter-animal bulk purchases.",
        "address_display": "Sherwood Park, AB",
        "latitude": 53.5233,
        "longitude": -113.3000,
        "categories": ["meat-poultry"],
        "sales_channels": ["delivery", "online", "farm_gate"],
        "certifications": ["pasture_raised"],
        "contact_website": "https://truegritbuffaloranch.com",
    },
    {
        "name": "McDonald Bison",
        "slug": "mcdonald-bison",
        "description": "Small family bison farm established 2019 offering quality Grade A bison meat at affordable prices direct to consumer.",
        "address_display": "Rocky Mountain House, AB",
        "latitude": 52.3753,
        "longitude": -114.9217,
        "categories": ["meat-poultry"],
        "sales_channels": ["farm_gate", "online"],
        "certifications": [],
        "contact_website": "https://mcdonaldbison.ca",
    },
    {
        "name": "BellMar Ranch and Gardens",
        "slug": "bellmar-ranch-and-gardens",
        "description": "Truly free-range pastured eggs from hens raised outdoors in mobile pasture coop moved every 3 days. Non-GMO feed. Quarterly egg CSA.",
        "address_display": "St. Albert, AB",
        "latitude": 53.6303,
        "longitude": -113.6271,
        "categories": ["eggs"],
        "sales_channels": ["csa", "farmers_market"],
        "certifications": ["free_range", "pasture_raised", "non_gmo"],
        "contact_website": "https://bellmarranch.com",
    },
    {
        "name": "Healing Homestead",
        "slug": "healing-homestead",
        "description": "Mixed livestock farm specializing in heritage breed poultry and pasture-raised pork. Free-range eggs from non-GMO, soy/corn-free fed hens.",
        "address_display": "Parkland County, AB",
        "latitude": 53.4667,
        "longitude": -114.1333,
        "categories": ["eggs", "meat-poultry"],
        "sales_channels": ["farm_gate", "delivery", "online"],
        "certifications": ["free_range", "pasture_raised", "non_gmo"],
        "contact_phone": "780-222-1756",
        "contact_website": "https://healinghomesteadstore.ca",
    },
    {
        "name": "Greidanus Honey Mill",
        "slug": "greidanus-honey-mill",
        "description": "Producing raw, unfiltered, unpasteurized honey since 1973 with hives in the southern Alberta foothills. Farm gate pickup Tuesdays and Thursdays.",
        "address_display": "High River, AB",
        "latitude": 50.5833,
        "longitude": -113.8667,
        "categories": ["honey-bee"],
        "sales_channels": ["farm_gate", "delivery", "online"],
        "certifications": [],
        "contact_website": "https://honeymill.ca",
    },
    {
        "name": "Paradis Honey Farm",
        "slug": "paradis-honey-farm",
        "description": "Seventh-generation family apiary operating 3,500 colonies. Unpasteurized, non-filtered honey and pollen straight from the honeycomb.",
        "address_display": "Girouxville, AB",
        "latitude": 55.7333,
        "longitude": -117.3833,
        "categories": ["honey-bee"],
        "sales_channels": ["farm_gate", "online"],
        "certifications": [],
        "contact_website": "https://paradishoney.com",
    },
    {
        "name": "Gramma Bee's Honey",
        "slug": "gramma-bees-honey",
        "description": "Edmonton area honey available at Bountiful Farmers Market and local grocery stores including Save-On Foods, Safeway, and Co-op.",
        "address_display": "Edmonton, AB",
        "latitude": 53.5461,
        "longitude": -113.4937,
        "categories": ["honey-bee"],
        "sales_channels": ["farmers_market"],
        "certifications": [],
        "contact_website": "https://grammabeeshoney.com",
    },
    {
        "name": "Pleasant Valley Honey Producers",
        "slug": "pleasant-valley-honey",
        "description": "Beekeepers offering pure quality 100% Canadian honey, wax, and pollination services in Wetaskiwin County.",
        "address_display": "Falun, AB",
        "latitude": 52.7833,
        "longitude": -113.1333,
        "categories": ["honey-bee"],
        "sales_channels": ["farm_gate", "online"],
        "certifications": [],
        "contact_website": "https://pleasantvalleyhoney.com",
    },
    {
        "name": "The Saskatoon Farm",
        "slug": "the-saskatoon-farm",
        "description": "30+ year family farm south of Calgary with U-pick berries, 100-seat restaurant, bakery, boutique, and garden centre. Sells saskatoon products, raw honey, and seasonal vegetables.",
        "address_display": "De Winton, AB",
        "latitude": 50.8500,
        "longitude": -113.9333,
        "categories": ["produce", "honey-bee", "experiences", "preserves"],
        "sales_channels": ["farm_gate", "u_pick"],
        "certifications": [],
        "contact_phone": "403-938-6245",
        "contact_email": "hello@saskatoonfarm.com",
        "contact_website": "https://www.saskatoonfarm.com",
    },
    {
        "name": "Broxburn Vegetables & Cafe",
        "slug": "broxburn-vegetables",
        "description": "80-acre farm east of Lethbridge with 3-acre greenhouse. U-pick strawberries and raspberries in summer. One of Alberta's largest commercial broccoli crops.",
        "address_display": "Lethbridge, AB",
        "latitude": 49.7000,
        "longitude": -112.7333,
        "categories": ["produce"],
        "sales_channels": ["farm_gate", "u_pick", "online", "farmers_market"],
        "certifications": ["no_spray"],
        "contact_phone": "403-327-0909",
        "contact_website": "https://www.broxburn-vegetables.com",
    },
    {
        "name": "The Jungle Farm",
        "slug": "the-jungle-farm",
        "description": "Family farm near Innisfail offering U-pick strawberries, pumpkins, and a 14-week vegetable box CSA program. Famous for extremely sweet berries.",
        "address_display": "Innisfail, AB",
        "latitude": 52.0000,
        "longitude": -113.9500,
        "categories": ["produce", "experiences"],
        "sales_channels": ["farm_gate", "u_pick", "csa"],
        "certifications": [],
        "contact_website": "https://thejunglefarm.com",
    },
    {
        "name": "Prairie Gardens & Adventure Farm",
        "slug": "prairie-gardens",
        "description": "Award-winning 35-acre working family farm 25 minutes NE of Edmonton. CSA programs for summer, fall, and winter. 50+ farm activities including corn maze and petting farm.",
        "address_display": "Bon Accord, AB",
        "latitude": 53.8333,
        "longitude": -113.4167,
        "categories": ["produce", "experiences"],
        "sales_channels": ["farm_gate", "u_pick", "csa"],
        "certifications": [],
        "contact_phone": "780-909-6601",
        "contact_email": "info@prairiegardens.org",
        "contact_website": "https://prairiegardens.org",
    },
    {
        "name": "Billyco Junction Gardens",
        "slug": "billyco-junction-gardens",
        "description": "Family-operated 40-acre U-pick farm established 1987. Grows honeyberries, strawberries, raspberries, saskatoons, cherries, plus 40+ vegetable types.",
        "address_display": "Lacombe, AB",
        "latitude": 52.4333,
        "longitude": -113.6500,
        "categories": ["produce", "honey-bee", "preserves"],
        "sales_channels": ["farm_gate", "u_pick"],
        "certifications": [],
        "contact_phone": "403-392-4892",
        "contact_website": "https://billycojunction.com",
    },
    {
        "name": "Pearson's Berry Farm",
        "slug": "pearsons-berry-farm",
        "description": "Founded 1969, recognized as the first commercial saskatoon berry orchard in the world. Famous for butter tarts, pies, apple ciders, and 100% pure fruit juices.",
        "address_display": "Bowden, AB",
        "latitude": 51.9333,
        "longitude": -114.0167,
        "categories": ["produce", "preserves"],
        "sales_channels": ["farm_gate", "farmers_market"],
        "certifications": [],
        "contact_phone": "403-224-3011",
        "contact_website": "https://pearsonsberryfarm.ca",
    },
    {
        "name": "Innisfail Growers",
        "slug": "innisfail-growers",
        "description": "Co-operative of five family farms in central Alberta growing healthy sustainable food. Everything sold is currently in season. Markets in Lacombe, Olds, Innisfail, and Calgary.",
        "address_display": "Innisfail, AB",
        "latitude": 52.0269,
        "longitude": -113.9500,
        "categories": ["produce"],
        "sales_channels": ["farmers_market"],
        "certifications": [],
        "contact_website": "https://www.innisfailgrowers.com",
    },
    {
        "name": "Vital Green Farms",
        "slug": "vital-green-farms",
        "description": "The only independent organic dairy farm left in Alberta. On-farm processing of organic Jersey cow's milk and cream. Also produces yoghurt and cheese.",
        "address_display": "Picture Butte, AB",
        "latitude": 49.8833,
        "longitude": -112.7833,
        "categories": ["dairy"],
        "sales_channels": ["farm_gate", "online"],
        "certifications": ["organic", "grass_fed"],
        "contact_website": "https://vitalgreen.ca",
    },
    {
        "name": "Rock Ridge Dairy",
        "slug": "rock-ridge-dairy",
        "description": "Federally inspected dairy processing facility milking 600 dairy goats. Produces whole natural goat milk, cheeses, plus specialty organic Jersey cow milk and cream.",
        "address_display": "Ponoka, AB",
        "latitude": 52.6833,
        "longitude": -113.5833,
        "categories": ["dairy"],
        "sales_channels": ["farm_gate", "online"],
        "certifications": ["organic"],
        "contact_website": "https://www.rockridgedairy.com",
    },
    {
        "name": "Lakeside Farmstead",
        "slug": "lakeside-farmstead",
        "description": "Artisan cheese made onsite using single-source milk. Farm retail store open Wed-Sat 10:30am-4:30pm.",
        "address_display": "Sturgeon County, AB",
        "latitude": 53.8000,
        "longitude": -113.7000,
        "categories": ["dairy"],
        "sales_channels": ["farm_gate"],
        "certifications": [],
        "contact_website": "https://lakesidefarmstead.com",
    },
]


class Command(BaseCommand):
    help = 'Seed the database with real Alberta farms'

    def handle(self, *args, **options):
        owner = User.objects.filter(is_superuser=True).first()
        if not owner:
            self.stderr.write('No superuser found. Create one first: python3 manage.py createsuperuser')
            return

        created = 0
        for data in FARMS:
            if Farm.objects.filter(slug=data['slug']).exists():
                continue

            cat_slugs = data.pop('categories')

            farm = Farm.objects.create(
                owner=owner,
                name=data['name'],
                slug=data['slug'],
                description=data.get('description', ''),
                latitude=data.get('latitude'),
                longitude=data.get('longitude'),
                address_display=data.get('address_display', ''),
                sales_channels=data.get('sales_channels', []),
                certifications=data.get('certifications', []),
                contact_phone=data.get('contact_phone', ''),
                contact_email=data.get('contact_email', ''),
                contact_website=data.get('contact_website', ''),
            )

            for slug in cat_slugs:
                try:
                    cat = Category.objects.get(slug=slug)
                    farm.categories.add(cat)
                except Category.DoesNotExist:
                    self.stderr.write(f'Category not found: {slug}')

            created += 1

        self.stdout.write(self.style.SUCCESS(f'Created {created} farms ({Farm.objects.count()} total)'))
