# Generated by Django 6.0.3 on 2026-03-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_display', models.CharField(blank=True, max_length=300)),
                ('address_full', models.CharField(blank=True, max_length=500)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal'), ('one_time', 'One-time event')], default='weekly', max_length=20)),
                ('day_of_week', models.CharField(blank=True, max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('season_start', models.DateField(blank=True, null=True)),
                ('season_end', models.DateField(blank=True, null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendors', models.ManyToManyField(blank=True, related_name='markets', to='farms.farm')),
            ],
            options={
                'ordering': ['next_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FarmProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('season_note', models.CharField(blank=True, max_length=200)),
                ('price_note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.category')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farms.farm')),
            ],
            options={
                'ordering': ['-is_available', 'name'],
            },
        ),
    ]
